/**
 * Turning one line of the Open Food Facts JSONL export into a `Product` row.
 *
 * Pure and database-free on purpose: the dump is multi-gigabyte and the only
 * practical way to be sure this handles the real shapes in it is to run it over
 * fixtures in a unit test. Nothing here reaches the network or Prisma — the
 * caller resolves unit tokens to ids and does the writing.
 *
 * The governing rule is the app's usual one: a field that cannot be understood
 * becomes `null`, never a guess. A pack size that will not parse leaves
 * `packQuantity` null and keeps `quantityRaw`, so the screen can still show
 * "500 g" as text even though nothing can do arithmetic with it.
 */

import { normalizeBarcode } from './barcode';

/** One parsed OFF row, with unit tokens left unresolved. */
export interface ParsedOffProduct {
  barcode: string;
  name: string;
  brands: string | null;
  quantityRaw: string | null;
  /** Decimal as a string, never a number — the usual reason. */
  packQuantity: string | null;
  /**
   * The unit as OFF wrote it ("g", "ml", "oz"), not a unit id. The importer
   * resolves it against the seeded unit table, because this file has no
   * database and the mapping belongs where the ids live.
   */
  packUnitToken: string | null;
  categoriesTags: string[];
  countriesTags: string[];
  imageSmallUrl: string | null;
  nutriments: Record<string, number>;
  nutriscoreGrade: string | null;
}

/** Why a row was not importable. Counted and reported by the CLI. */
export type SkipReason =
  | 'unparseable-json'
  | 'no-barcode'
  | 'no-name'
  | 'country-filtered';

export type OffRowResult =
  | { ok: true; product: ParsedOffProduct }
  | { ok: false; reason: SkipReason };

/**
 * The per-100g nutriment keys worth keeping.
 *
 * OFF's `nutriments` object carries every value in several representations at
 * once — per-serving, per-100g, the original unit, the prepared variant — and
 * runs to dozens of keys on a well-filled product. Storing all of it for two
 * million rows is a large multiple of the useful data, so this keeps the
 * per-100g slice, which is the basis every nutrition feature would work from
 * anyway. The values are stored exactly as OFF gives them; only the selection
 * is ours.
 */
const NUTRIMENT_KEYS = [
  'energy-kcal_100g',
  'energy_100g',
  'fat_100g',
  'saturated-fat_100g',
  'carbohydrates_100g',
  'sugars_100g',
  'fiber_100g',
  'proteins_100g',
  'salt_100g',
  'sodium_100g',
] as const;

/**
 * Parses one JSONL line.
 *
 * A malformed line is reported, not thrown: the export is generated by a live
 * community database and one bad row a few million lines in should not end an
 * import that has been running for twenty minutes.
 *
 * `countries` filters to OFF country tags (`en:united-states`). An empty filter
 * means "keep everything".
 */
export function parseOffLine(line: string, countries: readonly string[] = []): OffRowResult {
  let raw: Record<string, unknown>;
  try {
    raw = JSON.parse(line) as Record<string, unknown>;
  } catch {
    return { ok: false, reason: 'unparseable-json' };
  }
  return parseOffRow(raw, countries);
}

/** The same, for an already-parsed object. Split out so tests can build one. */
export function parseOffRow(
  raw: Record<string, unknown>,
  countries: readonly string[] = [],
): OffRowResult {
  const barcode = normalizeBarcode(asString(raw.code));
  if (!barcode) return { ok: false, reason: 'no-barcode' };

  // A product with no name is not showable and not searchable; the barcode
  // alone tells the cook nothing. OFF has plenty of these — rows created by a
  // scan that was never filled in.
  const name = pickName(raw);
  if (!name) return { ok: false, reason: 'no-name' };

  const countriesTags = asStringArray(raw.countries_tags);
  if (countries.length > 0 && !countriesTags.some((tag) => countries.includes(tag))) {
    return { ok: false, reason: 'country-filtered' };
  }

  const quantityRaw = asString(raw.quantity);
  const pack = parsePackSize(quantityRaw);

  return {
    ok: true,
    product: {
      barcode,
      name,
      brands: asString(raw.brands),
      quantityRaw,
      packQuantity: pack?.quantity ?? null,
      packUnitToken: pack?.unitToken ?? null,
      categoriesTags: asStringArray(raw.categories_tags),
      countriesTags,
      // Built from `images`, not read from a field — see `buildImageUrl`. The
      // raw code is passed deliberately, not the normalized barcode.
      imageSmallUrl: buildImageUrl(asString(raw.code), raw.images),
      nutriments: pickNutriments(raw.nutriments),
      nutriscoreGrade: pickGrade(raw.nutriscore_grade),
    },
  };
}

/**
 * The best available product name.
 *
 * `product_name` is whatever language the contributor used, so an English name
 * is preferred where OFF has one. Falling back to the generic name matters more
 * than it looks: on own-brand goods it is often the only thing filled in.
 */
function pickName(raw: Record<string, unknown>): string | null {
  for (const key of ['product_name_en', 'product_name', 'generic_name_en', 'generic_name']) {
    const value = asString(raw[key]);
    if (value) return value.slice(0, 200);
  }
  return null;
}

/** Where OFF serves product images from. */
const IMAGE_HOST = 'https://images.openfoodfacts.org/images/products';

/**
 * The 200px front-of-pack image URL, or null when the product has no picture.
 *
 * **There is no image URL field in the JSONL export.** `image_small_url` exists
 * in the OFF *API* responses and it is easy to assume the dump matches — it
 * does not, and the mistake is silent: every row parses fine and every product
 * simply has no picture. The dump instead carries an `images` object, and the
 * URL has to be constructed:
 *
 *     images.selected.front.<lang> = { rev: "4", imgid: "1", sizes: {...} }
 *     -> {host}/{path}/front_{lang}.{rev}.200.jpg
 *
 * Two details that are wrong if guessed:
 *
 * - **The path uses the raw code, not the normalized barcode.** OFF derives the
 *   directory from the code exactly as it stores it, splitting into groups of
 *   three. A 12-digit code stored as `041196010184` lives under
 *   `041/196/010/184`; padding it to EAN-13 first would ask for
 *   `004/119/601/0184`, which does not exist. So the normalization that makes
 *   *scanning* work must not be applied here.
 * - **Codes of 8 digits or fewer are not split at all** and form the directory
 *   whole.
 *
 * English is preferred where OFF has it, since that is what the UI is in;
 * otherwise the first language present, because a picture of the pack is useful
 * whatever the label language.
 */
export function buildImageUrl(rawCode: string | null, images: unknown): string | null {
  if (!rawCode || !images || typeof images !== 'object') return null;

  const front = (images as { selected?: { front?: unknown } }).selected?.front;
  if (!front || typeof front !== 'object') return null;

  const byLanguage = front as Record<string, { rev?: unknown } | undefined>;
  const language =
    'en' in byLanguage ? 'en' : Object.keys(byLanguage).find((key) => byLanguage[key]);
  if (!language) return null;

  // `rev` is the revision the selected image was taken at; the URL is wrong
  // without it, and OFF sends it as a string in some rows and a number in
  // others.
  const rev = byLanguage[language]?.rev;
  const revision =
    typeof rev === 'string' ? rev.trim() : typeof rev === 'number' ? String(rev) : '';
  if (!revision) return null;

  return `${IMAGE_HOST}/${imagePath(rawCode)}/front_${language}.${revision}.200.jpg`;
}

/** Groups of three then the remainder — OFF's directory layout for a code. */
function imagePath(code: string): string {
  if (code.length <= 8) return code;
  const match = code.match(/^(.{3})(.{3})(.{3})(.+)$/);
  return match ? `${match[1]}/${match[2]}/${match[3]}/${match[4]}` : code;
}

/** OFF writes grades lower-case, but not consistently; and "unknown" is not a grade. */
function pickGrade(value: unknown): string | null {
  const grade = asString(value)?.toLowerCase();
  if (!grade) return null;
  return /^[a-e]$/.test(grade) ? grade : null;
}

function pickNutriments(value: unknown): Record<string, number> {
  if (!value || typeof value !== 'object') return {};
  const source = value as Record<string, unknown>;

  const result: Record<string, number> = {};
  for (const key of NUTRIMENT_KEYS) {
    const number = asFiniteNumber(source[key]);
    if (number !== null) result[key] = number;
  }
  return result;
}

/**
 * How a pack size is written, and what this makes of it.
 *
 * OFF's `quantity` is free text typed by contributors, so it arrives as "500 g",
 * "500g", "1,5 L", "2 x 125 g", "1 kg (2.2 lb)" and much worse. This takes the
 * first number-and-unit pair it can find and multiplies through an explicit
 * "N x" prefix, because a 6 x 330 ml pack really does hold 1980 ml and storing
 * 330 would be wrong in a way nothing downstream could detect.
 *
 * Anything it cannot read returns null rather than a partial guess. `quantityRaw`
 * keeps the original either way, so nothing is lost by declining.
 */
export function parsePackSize(
  raw: string | null,
): { quantity: string; unitToken: string } | null {
  if (!raw) return null;

  // Commas are decimal separators across most of OFF's contributor base
  // ("1,5 L"), but thousands separators in en-US ("1,000 g"). A comma with
  // exactly three digits after it and a digit before is the thousands case.
  const text = raw
    .toLowerCase()
    .replace(/(\d),(\d{3})\b/g, '$1$2')
    .replace(/,/g, '.');

  // Spelled-out units are alternatives, not an afterthought: OFF is typed by
  // hand and "230 gram" is as common as "230 g". Longest-first within each
  // prefix, so "kg" is not read as "k" followed by nothing and "grams" is not
  // read as "g" followed by a failed word boundary.
  const match = text.match(
    /(?:(\d+(?:\.\d+)?)\s*[x×]\s*)?(\d+(?:\.\d+)?)\s*(fl\s*oz|fluid\s*ounces?|kilograms?|kilos?|kg|milligrams?|mg|grams?|grammes?|g|pounds?|lbs?|ounces?|oz|millilitres?|milliliters?|ml|decilitres?|deciliters?|dl|centilitres?|centiliters?|cl|litres?|liters?|l)\b/,
  );
  if (!match) return null;

  const [, multiplierRaw, amountRaw, unitRaw] = match;

  const amount = Number(amountRaw);
  const multiplier = multiplierRaw ? Number(multiplierRaw) : 1;
  if (!Number.isFinite(amount) || !Number.isFinite(multiplier)) return null;
  if (amount <= 0 || multiplier <= 0) return null;

  const total = amount * multiplier;
  // Guards against "2024 g" from a stray year and similar nonsense reaching the
  // Decimal(12,4) column as something that cannot be stored.
  if (total > 99_999_999) return null;

  return {
    // Trailing zeroes trimmed so 1.50 stores as "1.5"; toFixed then strip is
    // what keeps 6 x 0.33 from arriving as 1.9800000000000002.
    quantity: trimNumber(total),
    unitToken: normalizeUnitToken(unitRaw),
  };
}

/**
 * Collapses OFF's many spellings onto one token per unit.
 *
 * Everything downstream — `off-units.ts`, and therefore the `packUnitId` on
 * every product row — keys off these tokens, so an unmapped spelling must fall
 * through as itself rather than being approximated onto a neighbouring unit.
 * It then fails to resolve, and the pack size is dropped with the raw text
 * kept, which is the honest outcome.
 */
const UNIT_SPELLINGS: Readonly<Record<string, string>> = {
  gram: 'g',
  grams: 'g',
  gramme: 'g',
  grammes: 'g',
  kilogram: 'kg',
  kilograms: 'kg',
  kilo: 'kg',
  kilos: 'kg',
  milligram: 'mg',
  milligrams: 'mg',
  pound: 'lb',
  pounds: 'lb',
  lbs: 'lb',
  ounce: 'oz',
  ounces: 'oz',
  millilitre: 'ml',
  millilitres: 'ml',
  milliliter: 'ml',
  milliliters: 'ml',
  litre: 'l',
  litres: 'l',
  liter: 'l',
  liters: 'l',
  decilitre: 'dl',
  decilitres: 'dl',
  deciliter: 'dl',
  deciliters: 'dl',
  centilitre: 'cl',
  centilitres: 'cl',
  centiliter: 'cl',
  centiliters: 'cl',
  floz: 'fl oz',
  fluidounce: 'fl oz',
  fluidounces: 'fl oz',
};

function normalizeUnitToken(token: string): string {
  const clean = token.replace(/\s+/g, '');
  return UNIT_SPELLINGS[clean] ?? clean;
}

function trimNumber(value: number): string {
  return value.toFixed(4).replace(/\.?0+$/, '');
}

function asString(value: unknown): string | null {
  if (typeof value !== 'string') return null;
  const trimmed = value.trim();
  return trimmed === '' ? null : trimmed;
}

function asStringArray(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return value.filter((entry): entry is string => typeof entry === 'string');
}

/**
 * OFF sends numbers as numbers in some rows and as strings in others, and sends
 * empty strings for "not filled in". NaN and Infinity would poison any later
 * arithmetic, so they are dropped rather than stored.
 */
function asFiniteNumber(value: unknown): number | null {
  if (typeof value === 'number') return Number.isFinite(value) ? value : null;
  if (typeof value === 'string' && value.trim() !== '') {
    const parsed = Number(value);
    return Number.isFinite(parsed) ? parsed : null;
  }
  return null;
}
