-- Replaces the nullable-householdId "global row" convention on unit/ingredient,
-- and the separately-named 'OFF Auto-Match' household, with one reserved
-- Household row at id 0 (SYSTEM_HOUSEHOLD_ID in @kitchen/shared-types).
--
-- Written by hand rather than generated by `prisma migrate dev`, which cannot
-- express "insert a specific id, then backfill, then tighten the column" as a
-- single diff. See CLAUDE.md for why `ingredient_name_trgm_idx` and
-- `ingredient_alias_alias_trgm_idx` (raw SQL, not in this migration) must never
-- be dropped by a future generated migration that sees them as drift.

-- 1. The sentinel household. Explicit id; Household.id is a Postgres identity
--    sequence starting at 1, so this insert never collides with it and the
--    sequence itself is untouched.
INSERT INTO "household" ("id", "name", "createdOn")
VALUES (0, 'System', now())
ON CONFLICT ("id") DO NOTHING;

-- 2. Backfill the global catalog onto the sentinel household.
UPDATE "unit" SET "householdId" = 0 WHERE "householdId" IS NULL;
UPDATE "ingredient" SET "householdId" = 0 WHERE "householdId" IS NULL;

-- 3. Fold the OFF auto-match household's bindings into the sentinel, then drop
--    that household. Where both already voted on the same barcode, keep the
--    sentinel's existing row and discard the auto-match one rather than
--    conflicting on (householdId, productId).
UPDATE "product_binding" pb
   SET "householdId" = 0
  FROM "household" h
 WHERE h."name" = 'OFF Auto-Match'
   AND pb."householdId" = h."id"
   AND NOT EXISTS (
     SELECT 1 FROM "product_binding" x
      WHERE x."householdId" = 0 AND x."productId" = pb."productId"
   );

DELETE FROM "product_binding" pb
 USING "household" h
 WHERE h."name" = 'OFF Auto-Match'
   AND pb."householdId" = h."id";

DELETE FROM "household" WHERE "name" = 'OFF Auto-Match';

-- 4. Tighten the columns now that every row has a real householdId.
ALTER TABLE "unit" ALTER COLUMN "householdId" SET NOT NULL;
ALTER TABLE "unit" ALTER COLUMN "householdId" SET DEFAULT 0;
ALTER TABLE "ingredient" ALTER COLUMN "householdId" SET NOT NULL;
ALTER TABLE "ingredient" ALTER COLUMN "householdId" SET DEFAULT 0;

-- 5. `ON DELETE SET NULL` is no longer legal on a NOT NULL column.
ALTER TABLE "unit" DROP CONSTRAINT "unit_householdId_fkey";
ALTER TABLE "ingredient" DROP CONSTRAINT "ingredient_householdId_fkey";
ALTER TABLE "unit" ADD CONSTRAINT "unit_householdId_fkey"
  FOREIGN KEY ("householdId") REFERENCES "household"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ingredient" ADD CONSTRAINT "ingredient_householdId_fkey"
  FOREIGN KEY ("householdId") REFERENCES "household"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- 6. The partial unique indexes existed only because Postgres treats NULLs as
--    distinct. Now that global rows carry a real value (0), the schema-level
--    @@unique([householdId, name]) / @@unique([householdId, slug]) constrain
--    them natively, and these are redundant.
DROP INDEX "unit_global_name_key";
DROP INDEX "ingredient_global_slug_key";
